### ISSUE TITLE
Incompatible with current save game format

### ISSUE THREAD

**Issue by Immortal2563** [epinter/tqrespec#40]
Here is my hero.
[Player.zip](https://github.com/epinter/tqrespec/files/8618033/Player.zip)

**Comment by epinter** [comment]
Thank you very much ! Tonight I will work on it.

**Comment by epinter** [comment]
Hi!

I was unable to test your Player.chr in game, because everytime I enter the game, it resets the difficulty to normal. I think is because the missing files. But I think it was sufficient for me to know what change in the savegame.

The file in the link below is a build of TQRespec that has some unreleased development code. Also, I had to change more things that I wanted because of the new savegame format, but I think is stable enough. I tested editing some characters and entering the game and everything was fine.

If you have any problem with it, would help if you could post the tqrespec.log (from your user temp folder), and the complete character savegame (with all files in the levels folder).

PLEASE, MAKE A FULL BACKUP OF YOUR SAVEGAME BEFORE TESTING.  :-)

https://1drv.ms/u/s!AqbcmbBetf3hgQhjgKsRYQT6ZSKp?e=74RrTb

**Comment by Bazylisek** [comment]
@epinter 

[tqrespec.log](https://github.com/epinter/tqrespec/files/8695059/tqrespec.log)

character folder:
https://drive.google.com/drive/folders/1L7p5S575YMrK09JbEdnXGPpXJLvvpWgc?usp=sharing

**Comment by epinter** [comment]
> @epinter
> 
> [tqrespec.log](https://github.com/epinter/tqrespec/files/8695059/tqrespec.log)
> 
> character folder: https://drive.google.com/drive/folders/1L7p5S575YMrK09JbEdnXGPpXJLvvpWgc?usp=sharing

This log was generated with the test build I posted here, or was with 0.11 ?

Thank you

**Comment by epinter** [comment]
I've done some tests with two diferent savegames from Ethernal Embers (new file format), and everything seems stable, before and after editing character with TQRespec. Before release a new version, I would like some tests with the build I've posted before, from this link:

https://1drv.ms/u/s!AqbcmbBetf3hgQhjgKsRYQT6ZSKp?e=74RrTb

**Comment by Bazylisek** [comment]
> > @epinter
> > [tqrespec.log](https://github.com/epinter/tqrespec/files/8695059/tqrespec.log)
> > character folder: https://drive.google.com/drive/folders/1L7p5S575YMrK09JbEdnXGPpXJLvvpWgc?usp=sharing
> 
> This log was generated with the test build I posted here, or was with 0.11 ?
> 
> Thank you

from the old 0.11

**Comment by Gethsemane2** [comment]
preliminary tests of the new release were positive, no error was reported and the program ran perfectly for me. Thanks for the fast response and great work!

**Comment by epinter** [comment]
> preliminary tests of the new release were positive, no error was reported and the program ran perfectly for me. Thanks for the fast response and great work!

Thanks for you help.

**Comment by epinter** [comment]
New version published. Thanks for all of you for the help with reporting and testing.

https://github.com/epinter/tqrespec/releases/tag/v0.11.1
